# Imagen base de Node
FROM node:20

# Instalar herramientas necesarias para scripts
RUN apt-get update && apt-get install -y curl jq && rm -rf /var/lib/apt/lists/*

# Crear directorio de trabajo en el contenedor
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# Dar permisos de ejecución a los scripts (si existen)
RUN chmod +x src/scripts/*.sh || true

EXPOSE 3000

CMD ["npm", "start"]
