# Imagen base: Usamos nginx-alpine por ser ligero
FROM nginx:alpine

# Eliminar el contenido por defecto de nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiar los archivos estáticos al directorio raíz de Nginx
COPY index.html /usr/share/nginx/html/
COPY applogin.css /usr/share/nginx/html/
COPY applogin.js /usr/share/nginx/html/

# CRÍTICO: Eliminar la configuración por defecto y copiar la nuestra
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.config /etc/nginx/conf.d/default.conf

# Exponer el puerto por defecto de Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]